### ISSUE TITLE
Odoo Session Expired

### ISSUE THREAD

**Issue by ghost** [saidimu/odoo#17]
Hello, 
I'm trying to execute some very simple methods but I get this error everytime. Does anyone know where it comes from and how I can solve this ? 
```

{ message: 'Odoo Session Expired',
    code: 100,
    data:
    { 
        debug: 'Traceback (most recent call last):  
                File "/home/odoo/src/odoo/saas-14/odoo/http.py", line 640, in _handle_exception    return super(JsonRequest, self)._handle_exception(exception)  
                File "/home/odoo/src/odoo/saas-14/odoo/addons/base/ir/ir_http.py", line 184, in _dispatch    
                auth_method = cls._authenticate(func.routing["auth"])  
                File "/home/odoo/src/odoo/saas-14/odoo/addons/base/ir/ir_http.py", line 112, in _authenticate    
                getattr(cls, "_auth_method_%s" % auth_method)()  
                File "/home/odoo/src/odoo/saas-14/odoo/addons/base/ir/ir_http.py", line 85, in _auth_method_user    
                raise http.SessionExpiredException("Session expired")
                SessionExpiredException: Session expired',
        exception_type: 'internal_error',
        message: 'Session expired',
        name: 'odoo.http.SessionExpiredException',
        arguments: [ 'Session expired' ] 
    } 
}
```

**Comment by ghost** [comment]
Ok I found the problem. I just forget to connect before calling the method lol. Sorry for this useless issue
